// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgbvmfxweaaazmazokjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYnZtZnh3ZWFhYXptYXpva2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTY1MzcsImV4cCI6MjA2MzU3MjUzN30.Z7PPFZ1TQOFw-w317ABBhCO7KvpgKEkudTYK0FRyMZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);